// Browser UI checks with a mocked native bridge; not website login evidence.
const {chromium} = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = process.env.MPD_TEST_ROOT || path.resolve(__dirname, '..');
(async () => {
  const browser = await chromium.launch({channel: process.env.MPD_TEST_BROWSER || 'msedge', headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1280,height:1000}});
    const errors=[]; page.on('pageerror', error => errors.push(error.message));
    await page.route('**/*', route => {
      const url=new URL(route.request().url());
      if(url.origin!=='https://mpd.test')return route.abort();
      const name=url.pathname==='/'?'index.html':url.pathname.slice(1);
      const file=path.join(root,'ui',name);
      return fs.existsSync(file)?route.fulfill({path:file}):route.fulfill({status:404,body:''});
    });
    await page.addInitScript({path:path.join(root,'tests/ui-fixture.js')});
    await page.goto('https://mpd.test/');
    await page.waitForSelector('.player-card');
    assert.equal(await page.locator('#run-status').textContent(),'Running');
    assert.equal(await page.locator('#source option[value="twitch"]').textContent(),'Twitch');
    assert.equal(await page.locator('.metrics .metric').count(),2);
    assert.equal(await page.getByRole('button',{name:/^Move .* (up|down)$/}).count(),0);
    assert(await page.locator('#connect').isDisabled());
    assert.equal(await page.locator('#client-id').count(),0);
    assert.equal(await page.locator('#viewer-signin').count(),0);
    await page.evaluate(() => {
      window.__fixture.settings.demo=false;
      window.__fixture.viewer={backend:'twitch-page',telemetry:false,media_controls:false,window_mute_controls:true,twitch_channel_page:true};
      for(const player of window.__fixture.players){player.window_muted=false;player.window_mute_override=false;}
      window.__fixture.player_origin='https://www.twitch.tv/';
    });
    await page.waitForFunction(() => !document.getElementById('connect').disabled);
    assert(await page.locator('#media-controls').isHidden());
    assert(await page.locator('#quality').isHidden());
    assert(await page.locator('#volume').isHidden());
    assert(await page.locator('#window-mute-controls').isVisible());
    assert(await page.locator('#twitch-page-note').isVisible());
    assert.match(await page.locator('#twitch-page-note').textContent(),/Dark Theme/);
    assert.match(await page.locator('#twitch-page-note').textContent(),/Volume and preferred quality remain inside each Twitch page/);
    assert.equal(await page.getByRole('button',{name:/page window/}).count(),3);
    await page.locator('#window-muted').check();
    await page.waitForFunction(() => window.__fixture.settings.muted === true);
    assert.deepEqual(await page.evaluate(() => window.__actions.at(-1)),{type:'set_window_mute',muted:true});
    assert.equal(await page.getByRole('button',{name:/page window/}).first().textContent(),'Muted globally');
    assert(await page.getByRole('button',{name:/page window/}).first().isDisabled());
    await page.locator('#window-muted').uncheck();
    await page.waitForFunction(() => window.__fixture.settings.muted === false);
    await page.getByRole('button',{name:'Mute bravo_demo page window'}).click();
    assert.deepEqual(await page.evaluate(() => window.__actions.at(-1)),{type:'set_window_mute',session:1,muted:true});
    await page.waitForFunction(() => document.querySelector('[aria-label="Unmute bravo_demo page window"]'));
    await page.locator('#window-muted').check();
    await page.waitForFunction(() => document.querySelector('[data-player-action="window-mute"][data-session="1"]')?.disabled);
    assert.equal(await page.locator('[data-player-action="window-mute"][data-session="1"]').textContent(),'Muted globally');
    await page.locator('#window-muted').uncheck();
    await page.waitForFunction(() => !document.querySelector('[aria-label="Unmute bravo_demo page window"]')?.disabled);
    assert.equal(await page.getByRole('button',{name:'Unmute bravo_demo page window'}).textContent(),'Unmute page');
    const sessionMute=page.getByRole('button',{name:'Unmute bravo_demo page window'});
    await sessionMute.focus();
    await page.evaluate(() => {window.__fixture.players[0].timer={state:'counting',remaining_seconds:59};});
    await page.waitForFunction(() => document.querySelector('.player-timer')?.textContent.includes('0:59'));
    assert.equal(await page.evaluate(() => document.activeElement?.dataset.playerAction),'window-mute');
    assert.equal(await page.evaluate(() => document.activeElement?.dataset.session),'1');
    await page.evaluate(() => {window.__rejectWindowMute=true;});
    await page.locator('#window-muted').focus();
    await page.locator('#window-muted').click();
    await page.waitForFunction(() => !document.getElementById('error').hidden&&!document.getElementById('window-muted').checked);
    assert.equal(await page.evaluate(() => document.activeElement?.id),'window-muted');
    assert.match(await page.locator('#error-text').textContent(),/Simulated native mute failure/);
    await page.evaluate(() => {window.__rejectWindowMute=false;});
    await page.evaluate(() => {
      window.__fixture.settings.muted=true;
      window.__fixture.players[0].window_muted=false;
    });
    const partialMute=page.locator('[data-player-action="window-mute"][data-session="1"]');
    await page.waitForFunction(() => document.querySelector('[data-player-action="window-mute"][data-session="1"]')?.textContent.includes('retry'));
    assert.equal(await partialMute.textContent(),'Unmuted · retry global mute');
    assert.equal(await partialMute.getAttribute('aria-label'),'bravo_demo page window is unmuted; global mute control is on');
    assert(await partialMute.isDisabled());
    await page.evaluate(() => {window.__fixture.settings.muted=false;});
    await page.evaluate(() => {window.__fixture.viewer={backend:'twitch-page',telemetry:false,media_controls:false,window_mute_controls:false,twitch_channel_page:true};});
    await page.waitForFunction(() => document.getElementById('window-mute-controls').hidden);
    assert.match(await page.locator('#twitch-page-note').textContent(),/unavailable on this platform/);
    assert.equal(await page.getByRole('button',{name:/page window/}).count(),0);
    await page.evaluate(() => {window.__fixture.viewer={backend:'twitch-embed',telemetry:true,media_controls:true,window_mute_controls:false,twitch_channel_page:false};});
    await page.waitForFunction(() => !document.getElementById('media-controls').hidden);
    assert(await page.locator('#twitch-page-note').isHidden());
    assert(await page.locator('#window-mute-controls').isHidden());
    await page.evaluate(() => {window.__fixture.viewer={backend:'twitch-page',telemetry:false,media_controls:false,window_mute_controls:true,twitch_channel_page:true};window.__actions=[];});
    await page.waitForFunction(() => document.getElementById('media-controls').hidden);
    assert.equal(await page.locator('#viewer-backend').textContent(),'twitch-page');
    assert.equal(await page.locator('#playing-heading').count(),0);
    assert.match(await page.locator('.player-state').first().textContent(),/Playback managed by Twitch/);
    await page.locator('#connect').click();
    await page.waitForFunction(() => window.__actions.length===1);
    assert.deepEqual(await page.evaluate(() => window.__actions),[{type:'connect'}]);
    await page.evaluate(() => {window.__fixture.auth_pending=true;});
    await page.waitForFunction(() => document.getElementById('connect').textContent==='Connecting Twitch…');
    assert(await page.locator('#connect').isDisabled());
    assert.equal(await page.locator('#disconnect').textContent(),'Cancel');
    await page.evaluate(() => {window.__fixture.user_code='TESTCODE';});
    await page.waitForFunction(() => document.getElementById('connect').textContent==='Continue in Twitch');
    await page.locator('#connect').click();
    assert.deepEqual(await page.evaluate(() => window.__actions.at(-1)),{type:'connect'});
    await page.locator('#disconnect').click();
    assert.deepEqual(await page.evaluate(() => window.__actions.at(-1)),{type:'disconnect'});
    await page.evaluate(() => {window.__fixture.auth_pending=false;window.__fixture.user_code=null;window.__fixture.connected_as='monitor_test';});
    await page.waitForFunction(() => document.getElementById('auth-status').textContent==='Monitoring as monitor_test');
    assert.equal(await page.locator('#connect').textContent(),'Reconnect Twitch');
    assert.equal(await page.locator('.player-card').count(),3);
    await page.evaluate(() => {window.__fixture.connected_as=null;window.__fixture.error='Could not remove saved authorization. Retry Disconnect.';});
    await page.waitForFunction(() => document.getElementById('auth-status').textContent==='Not connected');
    assert(await page.locator('#disconnect').isEnabled());
    await page.locator('#disconnect').click();
    assert.deepEqual(await page.evaluate(() => window.__actions.at(-1)),{type:'disconnect'});
    assert.match(await page.locator('#auth-panel').textContent(),/Disconnect removes saved monitoring authorization/);
    assert.deepEqual(errors,[]);
    console.log('PASS unified Connect, pending/reopen/cancel states, no client ID override, monitoring-only status, player cards retained, no JS errors');
  } finally {await browser.close();}
})().catch(error => {console.error(error);process.exitCode=1;});
